[package]
name = "spongbobcli"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.13"
which = "4.2.4"
chttp = "0.5.5"
scraper = "0.12.0"
colored = "2.0.0"
terminal-spinners = "0.3.2"